name: Deploy Next.js Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present # build app
    # - run: npm run lint ->  optional, if you have lint script in package.json
    - run: npm test # optiona, if you have tests
    
  # Step 7: Set up Docker Buildx (required for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

  # Step 8: Log in to Docker Hub (use secrets for credentials)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set in GitHub Secrets

   # Step 9: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t your-username/your-image-name:${{ github.sha }} .
        # Optionally tag the image with commit SHA or 'latest'
        # docker build -t your-username/your-image-name:latest .

    # Step 10: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push your-username/your-image-name:${{ github.sha }}
        # Optionally push the latest tag as well
        # docker push your-username/your-image-name:latest
